version: '3'
services:
  app:
    build:
      context: .
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_started
    environment:
      APOD_DB_HOST: db
      APOD_DB_NAME: ${APOD_DB_NAME}
      APOD_DB_USER: ${APOD_DB_USER}
      APOD_DB_PASSWORD: ${APOD_DB_PASSWORD}
      APOD_DB_PORT: ${APOD_DB_PORT}
      NASA_APOD_LINK: ${NASA_APOD_LINK}
      NASA_API_KEY: ${NASA_API_KEY}

  db:
    image: postgres
    ports:
      - '${APOD_DB_PORT}:${APOD_DB_PORT}'
    environment:
      POSTGRES_PASSWORD: ${APOD_DB_PASSWORD}
      POSTGRES_USER: ${APOD_DB_USER}
      POSTGRES_DB: ${APOD_DB_NAME}